mypersonalweb/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from . import views


app_name='core'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'), 
    path('uploadresume/', views.PDF_form_upload, name='uploadresume'),
    path('success/', views.SuccessTemplateView.as_view(), name='success'),
    path('contact/', views.ContactTemplateView.as_view(), name='contact'),
    path('post/all', views.ProjectListView.as_view(), name='project_all'),
    path('post/<int:pk>/', views.ProjectDetailView.as_view(), name='project_single'),
    path('post/create/', views.CreateProjectPostView.as_view(), name='create'),
    path('post/<int:pk>/delete/', views.DeleteProjectPostView.as_view(), name='delete_post'),
    path('post/<int:pk>/edit/', views.UpdateProjectPostView.as_view(), name='update_post'),
]

mypersonalweb/mypersonalweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('core/', include('core.urls'), name='core'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
        
    ]+ urlpatterns

mypersonalweb/core/models.py
from django.db import models
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.db.models.signals import pre_save
from .storage import OverwriteStorage
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from django.contrib.auth import get_user_model
User1 = get_user_model()
##allows for markdown / links in post
##
import misaka
import os

from django.conf import settings
from django.core.files.storage import Storage

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):
       
    def __str__(self):
        ##username defiend with .User
        ##
        return "@{}".format(self.username)


class PDFDocument(models.Model):
    name = models.CharField(max_length=100, blank=False, default='Document')
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='resume/', storage=OverwriteStorage())
    uploaded_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    
    def __str__(self):
        return self.name

##post project should only work for auth.User
##will need to make sure it only works with admin
##
class ProjectsPost(models.Model):
    author = models.ForeignKey(User1, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=False, default='Post Title')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    ##need to add image file
    ##
    
    def __str__(self):
        return self.message
    
    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)
        
    ##this goes to detail View
    ##
    def get_absolute_url(self):
        return reverse("core:project_single", kwargs={
                                               'pk':self.pk})
        
    class Meta:
        ##shows most recent first
        ##
        ordering= ['-created_at']
        
        ##every message is uniquely linked to user
        ##
        unique_together = ['author', 'message']

mypersonalweb/core/forms.py
from django.contrib.auth import get_user_model
from .models import PDFDocument
from django import forms

from .models import ProjectsPost
##if i want user to be able to create an account
##
##from django.contrib.auth.forms import UserCreationForm


class PDFDocumentForm(forms.ModelForm):
    class Meta:
        model = PDFDocument
        fields = ('name', 'description', 'document', )
        
        
class PostForm(forms.ModelForm):
    class Meta:
        ##model form is based off on
        ##
        model = ProjectsPost
        
        ##fields user can interact with
        ##
        fields = ('author', 'title', 'message')
        
        ##used to overwrite default values
        ##
        widgets ={
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'message':forms.Textarea(attrs={'class':'medium-editor-textarea'}),
        }
        

mypersonalweb/core/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import PDFDocument
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin
from django.utils.decorators import method_decorator
from django.contrib.auth import get_user_model
User = get_user_model()

from django.utils import timezone
from .forms import PDFDocumentForm, PostForm
from .models import ProjectsPost


##test url to show upload was success
##  
class SuccessTemplateView(LoginRequiredMixin, generic.TemplateView):
    template_name = "core/success.html"
    
    def get_object(self):
        return self.request.user

class ContactTemplateView(generic.TemplateView):
    template_name = "core/contact.html"
    
    # def get_object(self):
    #     return self.request.user

class ProjectListView(generic.ListView):
    paginate_by = 5  # if pagination is desired
    model = ProjectsPost
    # template_name = "core/project_list.html"
    select_related = ('user', 'title', 'message', 'created_at')
   
    # select_related = ['user', 'message']
    
    # def get_queryset(self):
        # context = super(BookListView, self).get_context_data(**kwargs)
        # return ProjectsPost.objects.filter(created_at__lte=timezone.now()).order_by('-created_at')
    
    
#@login_required
class CreateProjectPostView(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    
    ##redirect to login or detail view
    ##
    login_url= reverse_lazy('core:login')
    edirect_field_name = reverse_lazy('core:project_single')
    
    ##use form created to create post
    ##
    form_class= PostForm
    
    ##use model
    ##
    model = ProjectsPost
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user= self.request.user
        self.object.save()
        return super().form_valid(form)
    
class UpdateProjectPostView(LoginRequiredMixin, generic.UpdateView):
    login_url='/login/'
    # success_url = reverse_lazy('core:project_single')
    form_class = PostForm
    model = ProjectsPost
    
class DeleteProjectPostView(LoginRequiredMixin, generic.DeleteView):
     model = ProjectsPost
     ##where to go after deleting
     ##
     success_url = reverse_lazy('core:project_all')
    
    

class ProjectDetailView(generic.DetailView):
    # template_name= 'core/projectpost_detail.html'
    model= ProjectsPost
    
    # def get_object(self, queryset=None):
    #     return get_object_or_404(PDFDocument, pk=pk)


##uploads PDF to resumes section
##

@login_required
def PDF_form_upload(request):
    if request.method == 'POST':
        form = PDFDocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:success'))
    else:
        form = PDFDocumentForm()
    return render(request, 'core/upload_resume.html', {
        'form': form
    })
   

mypersonalweb/mypersonalweb/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "index.html"
    
    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

class ThanksPage(TemplateView):
    template_name = 'thanks.html'
    

mypersonalweb/core/templates/core/_post.html
<!-- direct injection so no extends -->

{% comment %} <div class="media">
    <!-- viewing their "profile" -->
	<h3 class="mr-5"><a href="{% url 'core:for_user' username=post.user.username %}">@{{ post.user.username }}</a></h3>

	<div class="media-body">
		<strong>{{ post.user.username }}</strong>
		<h5>{{ post.message_html|safe }}</h5>
			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
			{% if post.group %}
			<span class="group-name">in <a href="#">{{ post.group.name }}</a></span>
			{% endif %}
		</h5>

		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="fa fa-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div> {% endcomment %}

mypersonalweb/core/templates/core/contact.html
{% extends 'core/core_base.html' %}

{% block content %}
<h1>Coming soon!</h1>
{% endblock %}

mypersonalweb/core/templates/core/core_base.html
{% extends 'base.html' %}
{%block content%}
{% block precontent %}{% endblock precontent %}

{%block postedcontent%}{%endblock postedcontent%}

{% block postcontent %}{% endblock postcontent %}

{%endblock content%}

mypersonalweb/core/templates/core/login.html
{%extends 'core/core_base.html'%}
{% comment %} makes forms look nicer {% endcomment %}
{% load bootstrap4 %}

{%block content%}

<div class="container">
    <h1>Log In</h1>
    <form method="POST" >
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button type="submit" class="btn btn-default">Login</button>
        {% endbuttons %}
    </form>
</div>

{%endblock%}

mypersonalweb/core/templates/core/projectspost_confirm_delete.html
{%extends 'core/core_base.html'%}

{%block postedcontent%}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object.title }}?</p>
        <input type="submit" class="btn btn-danger" value="Delete">
    </form>
{%endblock%}

mypersonalweb/core/templates/core/projectspost_detail.html
{% extends 'core/core_base.html' %}

{% block precontent %}
    <div class='jumbotron'>Coming soon!</div>

{% endblock precontent %}



{%block postedcontent%}


    <h1 class="posttitle loader">{{projectspost.title}}</h1>
    <h4>By: {{projectspost.author}}</h4>
    <p>Published: {{ projectspost.created_at|date }}</p>

    <!-- <div class='date postdate'>{{projectpost.created_at}}</div> -->

    <p class="postcontent">{{projectspost.message|safe|linebreaksbr}}</p>

{%endblock postedcontent%}




{% block postcontent %}
    {%if user.is_authenticated%}
        <a href="{% url 'core:update_post' pk=projectspost.pk %}" class="btn btn-primary btn-warning">
            <span class="fa fa-edit"> </span> Edit
        </a>

        <a href="{% url 'core:delete_post' pk=projectspost.pk %}" class="btn btn-primary btn-danger">
            <span class="fa fa-remove"> </span> Remove
        </a>

    {%endif%}

{% endblock postcontent %}

mypersonalweb/core/templates/core/projectspost_form.html
{% extends 'core/core_base.html' %}
{% load bootstrap4 %}


{% block postedcontent %}
	<h4>Create new Project Post!</h4>

	<form class = 'post-form' method="post">
		{% csrf_token %}
		{{ form.as_p }}
		
		{% buttons %}
			<button type="submit" class="btn btn-primary btn-large">Post</button>
		{% endbuttons %}
	</form>

{% endblock %}

mypersonalweb/core/templates/core/projectspost_list.html
{% extends 'core/core_base.html' %}

{% block postedcontent %}

<div class='jumbotron'>Currently in Development!</div>

    {% for post in  page_obj %}
        <div class='card' >
            <div class='card-body'>
                <h1 class='card-title'><a class="card-link btn btn-primary" href="{% url 'core:project_single' post.pk %}">{{ post.title }}</a></h1>
            

                <p>Post: {{ post.message|truncatewords:20 }}</p>
                <p>Author: {{ post.author }}</p>
                <p>Published: {{ post.created_at|date }}</p>
                {%if user.is_authenticated%}
                    <a href="{% url 'core:update_post' pk=post.pk %}" class="btn btn-primary btn-warning">
                        <span class="fa fa-edit"> </span> Edit
                    </a>
            
                    <a href="{% url 'core:delete_post' pk=post.pk %}" class="btn btn-danger">
                        <span class="fa fa-remove"> </span> Remove
                    </a>
        
                {%endif%}
            </div>
        </div>
    {%endfor%}


{% endblock postedcontent %}

{% block postcontent %}
 
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

{% endblock postcontent %}

mypersonalweb/core/templates/core/success.html
{% extends 'core/core_base.html' %}

{% block content %}
<h1>Success! File Uploaded.</h1>
{% endblock %}

mypersonalweb/core/templates/core/upload_resume.html
{% extends 'core/core_base.html' %}



{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

mypersonalweb/templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% comment %} bootstrap4 {% endcomment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- master CSS -->
    <link rel="stylesheet" href="{% static 'mypersonalweb/css/master.css'%}">

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">

    <title>Document</title>
</head>
<body>

<!--  fixed-top -->
  <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
    <div class="container">
      <div class="navbar-nav align-items-center">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>
      </div>
      <div class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'core:project_all' %}" class="btn btn-simple">Projects</a>
          <a class="nav-item nav-link" href="{% url 'core:create'%}" class="btn btn-simple">Create Post</a>
          <a class="nav-item nav-link" href="{% url 'core:uploadresume'%}" class="btn btn-simple">Upload Resume</a>
          <a class="nav-item nav-link" href="{% url 'admin:index' %}" class="btn btn-simple">Admin</a>
          <a class="nav-item nav-link" href="{% url 'core:logout' %}" class="btn btn-simple">Sign Out</a>
          {% comment %} <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a> {% endcomment %}
        {% else %}
          <a class="nav-item nav-link" href="{% url 'core:project_all' %}" class="btn btn-simple">Projects</a>
          <a class="nav-item nav-link" href="" class="btn btn-simple">Resume</a>
          <a class="nav-item nav-link" href="{% url 'core:contact' %}" class="btn btn-simple">Contact</a>
          <a class="nav-item nav-link" href="https://github.com/bennergarrett"class="btn btn-simple"><span class='fab fa-github fa-lg'></span></a>
          <a class="nav-item nav-link" href="https://www.linkedin.com/in/bennergarrett/" class="btn btn-simple"><span class='fab fa-linkedin fa-lg'></span></a>
          <a class="nav-item nav-link" href="{% url 'core:login' %}" class="btn btn-simple">Sign In</a>

          {% comment %} <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a> {% endcomment %} 
        {% endif %}
      </div>
    </div>
  </nav>

  <div class='container'>
    {%block content%}

    {%endblock%}
  </div>

</body>
</html>

mypersonalweb/templates/index.html
{%extends 'base.html' %}

{%block content%}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Welcome to the Front Page!</h1>
      <p class="lead">This place houses the projects I'm working on!</p>
    </div>
  </div>

  <div class="container">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed rem nam excepturi cum ipsa nihil, asperiores illum fugiat doloribus eum libero et ut consequuntur ab est aliquid exercitationem atque unde?</p>

  </div>


{%endblock%}

mypersonalweb/templates/thanks.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thanks for visiting, come back soon!</h1>
{% endblock content %}